/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ScanHistory = IDL.Record({
  'itemsCleaned' : IDL.Nat,
  'date' : Time,
  'mbFreed' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AppSettings = IDL.Record({
  'theme' : IDL.Variant({ 'dark' : IDL.Null, 'light' : IDL.Null }),
  'notificationsEnabled' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'avatarColor' : IDL.Text,
});
export const SecurityScan = IDL.Record({
  'threatsFound' : IDL.Nat,
  'lastScanDate' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addScanHistory' : IDL.Func([ScanHistory], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllScanHistoriesByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ScanHistory)],
      ['query'],
    ),
  'getAppSettings' : IDL.Func([], [IDL.Opt(AppSettings)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLastScanHistory' : IDL.Func([IDL.Nat], [IDL.Vec(ScanHistory)], ['query']),
  'getScanCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getScanHistory' : IDL.Func([], [IDL.Vec(ScanHistory)], ['query']),
  'getSecurityScan' : IDL.Func([], [IDL.Opt(SecurityScan)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveAppSettings' : IDL.Func([AppSettings], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveSecurityScan' : IDL.Func([SecurityScan], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ScanHistory = IDL.Record({
    'itemsCleaned' : IDL.Nat,
    'date' : Time,
    'mbFreed' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AppSettings = IDL.Record({
    'theme' : IDL.Variant({ 'dark' : IDL.Null, 'light' : IDL.Null }),
    'notificationsEnabled' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'avatarColor' : IDL.Text,
  });
  const SecurityScan = IDL.Record({
    'threatsFound' : IDL.Nat,
    'lastScanDate' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addScanHistory' : IDL.Func([ScanHistory], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllScanHistoriesByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ScanHistory)],
        ['query'],
      ),
    'getAppSettings' : IDL.Func([], [IDL.Opt(AppSettings)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLastScanHistory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ScanHistory)],
        ['query'],
      ),
    'getScanCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getScanHistory' : IDL.Func([], [IDL.Vec(ScanHistory)], ['query']),
    'getSecurityScan' : IDL.Func([], [IDL.Opt(SecurityScan)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveAppSettings' : IDL.Func([AppSettings], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveSecurityScan' : IDL.Func([SecurityScan], [], []),
  });
};

export const init = ({ IDL }) => { return []; };